<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Orange HR Test Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>nick.vaughan@csiro.au;preetha.mohan@csiro.au;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>69bd9c83-8cb1-41b9-a3e2-1d426e129b8c</testSuiteGuid>
   <testCaseLink>
      <guid>27f0cb9c-cc99-4816-948e-29cbcdba3027</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CSIRO Test</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f55e4ab-56c6-49cf-9f87-7945308caf85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1a5c5c0-2e99-4110-afbd-8947b3770dec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a1a2705-85c3-489a-937e-bafa6340cb20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>596d7934-22d7-4963-b723-36771bc5d77d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b7fb5b94-7f0b-40a2-9df3-ea1ec71cd76c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CSIRO Test 2</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f55e4ab-56c6-49cf-9f87-7945308caf85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1a5c5c0-2e99-4110-afbd-8947b3770dec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a1a2705-85c3-489a-937e-bafa6340cb20</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>94f90254-47bd-4720-b85a-42b4c3daaf14</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GetPostCode</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
