<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sign in_fui-Image ___1mnpq15 fj3muxo f1_26bc44</name>
   <tag></tag>
   <elementGuidId>c7a65e7e-7cca-40de-90ff-fd96f2060f3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='outer']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.fui-Image.___1mnpq15.fj3muxo.f1akhkt.f1aperda.f1lxtadh.f1fabniw.f1ewtqcl.f14t3ns0.f1ps3kmd.f14xojzb.f1l02sjl.fly5x3f.f19dog8a.fh0xodd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1a810ed1-856c-4d8c-bd9f-0b7f96017fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://logincdn.msftauth.net/shared/5/js/../images/fluent_web_light_57fee22710b04cebe1d5.svg</value>
      <webElementGuid>d0a4e851-056f-486f-a136-f3ee56f7a7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fui-Image ___1mnpq15 fj3muxo f1akhkt f1aperda f1lxtadh f1fabniw f1ewtqcl f14t3ns0 f1ps3kmd f14xojzb f1l02sjl fly5x3f f19dog8a fh0xodd</value>
      <webElementGuid>e68951bb-2de9-4a86-bca8-3c73a232b321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>e38f82b3-1b69-4984-a516-1706a32febaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outer&quot;)/img[@class=&quot;fui-Image ___1mnpq15 fj3muxo f1akhkt f1aperda f1lxtadh f1fabniw f1ewtqcl f14t3ns0 f1ps3kmd f14xojzb f1l02sjl fly5x3f f19dog8a fh0xodd&quot;]</value>
      <webElementGuid>bede6d3c-ece8-423a-bd3f-9190791c12df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outer']/img</value>
      <webElementGuid>5d394806-7e82-4516-a075-c21b5313cfa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>b885e782-22b8-4ea9-8cba-af6135402c54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
