<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Security</name>
   <tag></tag>
   <elementGuidId>e6600fb9-a4f4-49fa-9896-ddca73cdb986</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='security-banner-title-column']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#security-banner-title-column</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Security&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>b41bd741-3aa6-4409-9ef3-16e16cd1649d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>security-banner-title-column</value>
      <webElementGuid>3ddde8d0-f60c-4b44-9ed0-7447d11ce86c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-332</value>
      <webElementGuid>fcab887c-9291-4168-a4e3-157163f03451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Security</value>
      <webElementGuid>73ab78f2-1c29-4e15-969c-5b73ec975185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;security-banner-title-column&quot;)</value>
      <webElementGuid>6097c10f-15c1-44fe-9542-833d398f8f94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='security-banner-title-column']</value>
      <webElementGuid>77741306-1ef0-4d48-9d08-15ba7c080895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content-landing-react']/div[2]/div/div[2]/div/div/div/div/div/div/div/div/div/div/ol/li/div/span/h1</value>
      <webElementGuid>4fe9d8c2-06fd-4da7-9647-1fb03aa19bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address book'])[1]/following::h1[1]</value>
      <webElementGuid>0cf8aafe-a97b-45c2-abd5-e63f642dd27b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment options'])[1]/following::h1[1]</value>
      <webElementGuid>66c83a00-a66c-4ab5-b0cc-5ed478f08654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change password'])[1]/preceding::h1[1]</value>
      <webElementGuid>6a599052-a125-4c0c-9a2a-a369e8a166b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last update: 02/04/2025'])[1]/preceding::h1[1]</value>
      <webElementGuid>d1b199c6-0ae4-4018-b92b-c612567d7e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>6ee39350-cc57-4237-82df-7079800f97a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
